[Settings]

yourbikeid = 581                 ; Enter your bike ID here [defauts = 581] integer value
yourboostVel = 55.0              ; Enter your boost velocity here [default = 50.0] float value
yourglideVel = 28.0              ; Enter your glide velocity [default = 28.0] float value
yourmaxBoostCharge = 250         ; Enter your maximum boost charge [default = 300] integer value
yourboostCharge = 250            ; Enter your current boost charge, should be same as your maximum boost charge [default = 300] integer value
yourmaxMgCharge = 200            ; Enter your maximum Machine Gun charge [default = 450] integer value
yourmgCharge = 200               ; Enter your current Machine Gun charge, should be same as your maximum Machine Gun charge [default = 450] integer value
yourMGAccuracyRange1 = -0.4      ;First value of Machine Gun accuracy Range [default = -0.4]
yourMGAccuracyRange2 = 0.4       ;Second value of Machine Gun accuracy Range [default = 0.4]

;IMPORTANT: DO NOT CHANGE SETTINGS IF YOU DONT KNOW WHAT YOU ARE DOING!
;tweak settings and find what suits you best. If you ever mess up, just come back here and reset the values to default.